import React from 'react';
import {
  Menu,
  Search,
  Brain as Psychology,
  Heart as Favorite,
  MessageCircle as ChatBubble,
  Bookmark,
  Sparkles as AutoAwesome,
  Sprout as PottedPlant,
  Users as Groups,
  MessageSquare as Chat,
  User as Person,
  Home,
  Share,
  MoreHorizontal as MoreHoriz,
  ArrowRight,
  ArrowRight as ArrowForward,
  Star,
  MoreVertical as MoreVert,
  SquarePen as EditSquare,
  Plus as Add,
  MapPin as LocationOn,
  Star as Stars,
  FileText as Article,
  MessageSquareQuote as QuestionAnswer,
  MessageSquareQuote,
  BellRing as NotificationsActive,
  Shield as Security,
  Settings,
  LogOut as Logout,
  ChevronRight,
  Send,
  Mic,
  PlusCircle as AddCircle,
  CheckCircle2 as CheckCircle,
  Calendar,
  Package as Inventory,
  ArrowLeft as ArrowBack,
  Loader2,
  X,
  AlertCircle,
  RefreshCw,
  Eye,
  EyeOff,
  Mail,
  Phone,
  Lock,
  TrendingUp,
  Users as UsersIcon,
  Award,
  Trash2,
  Trash2 as Delete
} from 'lucide-react';

export {
  Menu,
  Search,
  Psychology,
  Favorite,
  ChatBubble,
  Bookmark,
  AutoAwesome,
  PottedPlant,
  Groups,
  Chat,
  Person,
  Home,
  Share,
  MoreHoriz,
  ArrowForward,
  ArrowRight,
  Star,
  MoreVert,
  EditSquare,
  Add,
  LocationOn,
  Stars,
  Article,
  QuestionAnswer,
  MessageSquareQuote,
  NotificationsActive,
  Security,
  Settings,
  Logout,
  ChevronRight,
  Send,
  Mic,
  AddCircle,
  CheckCircle,
  Calendar,
  Inventory,
  ArrowBack,
  Loader2,
  X,
  AlertCircle,
  RefreshCw,
  Eye,
  EyeOff,
  Mail,
  Phone,
  Lock,
  TrendingUp,
  UsersIcon as Users,
  UsersIcon,
  Award,
  Trash2,
  Trash2 as Delete,
  Person as User
};
